development: &my_settings
  #enable_star: true  #   removed in new documentation
  min_prefix_len: 3   #   search*
  #min_infix_len: 0   #   *search
  #min_word_len: 0    #   *search*
  charset_type: utf-8 #   also removed in new doc
  morphology: stem_ru
test:
  <<: *my_settings
  mysql41: 9307
production:
  <<: *my_settings